name: Deploy Timeboxed

on:
  push:
    branches: [ "development" ]

jobs:
  get-timebox:
    name: Determine whether job can run
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Time
        id: current-time
        uses: josStorer/get-current-time@v2.1.1

      - name: Should Run
        env: 
          HOUR: "${{ steps.current-time.outputs.hour }}" # This is in UTC
          LOWER_BOUND: 14 # 10 am EST
          UPPER_BOUND: 21 # 5 pm EST
        run: |
          if (( $HOUR >= $LOWER_BOUND && $HOUR < $UPPER_BOUND )); then echo "SHOULD_RUN=y" >> $GITHUB_ENV; else echo "SHOULD_RUN=n" >> $GITHUB_ENV; fi 
             
      - name: Test Should Run
        env:
          JENKINS_USER: gabriel
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
          JENKINS_URL: "https://jenkins.elitegamer.gg/job/elitegamer_new_ui_build_job/buildWithParameters"
        if: ${{ env.SHOULD_RUN == 'y' }}
        run: curl -X POST $JENKINS_URL --user $JENKINS_USER:$JENKINS_API_TOKEN --data BRANCH=development --data ENVIRONMENT=groopview
