name: Deploy Timeboxed

on:
  push:
    branches: [ "master" ]

jobs:
  get-timebox:
    name: Determine whether job can run
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Time
        id: current-time
        uses: josStorer/get-current-time@v2.1.1
        with:
          utcOffset: "−05:00" # EST

      - name: Should Run
        env: 
          HOUR: "${{ steps.current-time.outputs.hour }}"
        run: |
          echo $HOUR
          if (( $HOUR >= 9 && $HOUR < 17 )); then echo "SHOULD_RUN=y" >> $GITHUB_ENV; else echo "SHOULD_RUN=n" >> $GITHUB_ENV; fi 
             
      - name: Test Should Run
        run: echo $SHOULD_RUN
