name: Deploy Timeboxed

on:
  push:
    branches: [ "master" ]

jobs:
  get-timebox:
    name: Determine whether job can run
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Time
        id: current-time
        uses: josStorer/get-current-time@v2.1.1
        with:
          format: H:m:s
          timezone: US/Eastern
          
      - name: test
        env:
          TIME: "${{ steps.current-time.outputs.formattedTime }}"
        run: echo $TIME
